In [1]:
!pip install -q -U torch watermark

In [2]:
%load_ext watermark
%watermark -v -p numpy,torch

Python implementation: CPython
Python version       : 3.8.5
IPython version      : 7.19.0

numpy: 1.19.2
torch: 1.8.0



In [3]:
import torch
import numpy as np

In [4]:
a = np.array([1, 2])
b = np.array([8, 9])

c = a + b
c

array([ 9, 11])

In [5]:
a = torch.tensor([1, 2])
b = torch.tensor([8, 9])

c = a + b
c

tensor([ 9, 11])

In [6]:

a = torch.tensor([1, 2])

a.numpy()

array([1, 2], dtype=int64)

In [7]:
a = np.array([1, 2])
torch.from_numpy(a)

tensor([1, 2], dtype=torch.int32)

In [8]:
torch.tensor([[1, 2], [2, 1]])

tensor([[1, 2],
        [2, 1]])

In [9]:
torch.FloatTensor([[1, 2], [2, 1]])


tensor([[1., 2.],
        [2., 1.]])

In [10]:
torch.tensor([[1, 2], [2, 1]], dtype=torch.bool)


tensor([[True, True],
        [True, True]])

In [11]:
torch.rand(3, 2)


tensor([[0.5968, 0.7243],
        [0.3205, 0.0034],
        [0.7394, 0.4268]])

In [12]:
torch.ones(3, 2)


tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [13]:
x = torch.tensor([[2, 3], [1, 2]])
print(x)
print(f'sum: {x.sum()}')

tensor([[2, 3],
        [1, 2]])
sum: 8


In [14]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
device


device(type='cpu')

In [15]:
x = torch.tensor([[2, 3], [1, 2]])
x.to(device)

tensor([[2, 3],
        [1, 2]])

In [16]:
x = x.to(device)

y = torch.tensor([[2, 2], [5, 1]])
y = y.to(device)

x.add(y)

tensor([[4, 5],
        [6, 3]])